# Generated by Django 5.1.6 on 2025-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=40)),
                ('Address', models.TextField()),
                ('Gender', models.CharField(max_length=10)),
                ('PhoneNo', models.BigIntegerField()),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vetRegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=40)),
                ('Photo', models.ImageField(upload_to='photos')),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.BigIntegerField()),
                ('LicenseFile', models.FileField(default=None, max_length=250, upload_to='media')),
                ('Address', models.TextField()),
                ('Specialization', models.CharField(max_length=20)),
                ('YearsOfExperience', models.IntegerField()),
                ('ClinicName', models.CharField(max_length=60)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
