# Generated by Django 5.1.6 on 2025-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetregisterdb',
            name='LicenseFile',
            field=models.FileField(default=None, max_length=250, upload_to='files'),
        ),
    ]
