# Generated by Django 5.1.6 on 2025-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_vetregisterdb_licensefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='shelterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelterName', models.CharField(max_length=70)),
                ('shelterEmail', models.EmailField(max_length=254)),
                ('shelterContact', models.BigIntegerField()),
                ('shelterAddress', models.TextField()),
                ('shelterLocationUrl', models.URLField(blank=True, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
