# Generated by Django 5.1.6 on 2025-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shelterdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='petCategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petCategory', models.CharField(max_length=20)),
            ],
        ),
    ]
