# Generated by Django 5.1.6 on 2025-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_petcategorydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterdb',
            name='shelterImage',
            field=models.ImageField(default='', null=True, upload_to='photos'),
        ),
    ]
