# Generated by Django 5.1.6 on 2025-03-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_shelterdb_shelterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='petDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=30)),
                ('petImage', models.ImageField(upload_to='photos')),
                ('petDescription', models.TextField()),
                ('petAge', models.IntegerField()),
                ('petBreed', models.CharField(max_length=30)),
                ('PetAddTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('ShelterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shelterdb')),
                ('petCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.petcategorydb')),
            ],
        ),
    ]
