# Generated by Django 5.1.6 on 2025-03-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_petdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=30)),
                ('petphoto', models.ImageField(upload_to='photos')),
                ('breed', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('symptoms', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('dateofappo', models.DateField()),
                ('timeofappo', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userregisterdb')),
                ('vetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vetregisterdb')),
            ],
        ),
    ]
