# Generated by Django 5.1.6 on 2025-03-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='petCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.petcategorydb'),
            preserve_default=False,
        ),
    ]
