# Generated by Django 5.1.6 on 2025-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_petcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='TimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeofappo',
            field=models.TimeField(),
        ),
    ]
