# Generated by Django 5.1.6 on 2025-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointment_timestamp_alter_appointment_timeofappo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetregisterdb',
            name='Price',
            field=models.IntegerField(default=500),
        ),
    ]
