# Generated by Django 5.1.6 on 2025-03-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_vetregisterdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
    ]
