# Generated by Django 5.1.6 on 2025-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.TextField(default='', null=True),
        ),
    ]
