# Generated by Django 5.1.6 on 2025-03-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_appointment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=30)),
                ('blogImage', models.ImageField(upload_to='photos')),
                ('Description', models.TextField()),
                ('TimeStamp', models.DateTimeField(auto_now=True)),
                ('vetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vetregisterdb')),
            ],
        ),
    ]
