# Generated by Django 5.1.6 on 2025-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='vetid',
            field=models.CharField(max_length=30),
        ),
    ]
