# Generated by Django 5.1.6 on 2025-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_blog_vetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='vetPhoto',
            field=models.ImageField(default='', null=True, upload_to='photos'),
        ),
    ]
