# Generated by Django 5.1.6 on 2025-03-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_report_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='timestamp',
        ),
    ]
