# Generated by Django 5.1.6 on 2025-03-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_report_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportFromVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(max_length=250, upload_to='files')),
                ('Description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('vetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vetregisterdb')),
            ],
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
