# Generated by Django 5.1.6 on 2025-03-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_reportfromvet_delete_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportFromVet',
        ),
    ]
