# Generated by Django 5.1.6 on 2025-03-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_reportfromvet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfromvet',
            name='appointmentid',
        ),
        migrations.RemoveField(
            model_name='reportfromvet',
            name='vetid',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='reportFromVet',
        ),
    ]
