# Generated by Django 5.1.6 on 2025-03-23 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_reportfromvet_appointmentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userregisterdb')),
            ],
        ),
        migrations.CreateModel(
            name='reportFromVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(max_length=250, upload_to='files')),
                ('Description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('vetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vetregisterdb')),
            ],
        ),
    ]
