# Generated by Django 5.1.6 on 2025-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_getintotouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterdb',
            name='shelterLocationUrl',
            field=models.TextField(null=True),
        ),
    ]
