# Generated by Django 5.1.6 on 2025-04-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_bankpaymentofvet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankPaymentofVet',
        ),
    ]
