# Generated by Django 5.1.6 on 2025-04-01 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_delete_bankpaymentofvet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('withdrawStatus', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('vetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vetregisterdb')),
            ],
        ),
    ]
