# Generated by Django 5.1.6 on 2025-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_withdrawvet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawvet',
            name='withdrawStatus',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
