# Generated by Django 5.1.6 on 2025-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_withdrawvet_withdrawstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawvet',
            name='withdrawStatus',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
    ]
